---
title: "Warming non-randomly speeds up food web fluxes in both an absolute and relative sense"
author:
  - James R. Junker:
      email: jrjunker@mtu.edu
      institute: [msu, glrc]
      correspondence: true
  - name: Wyatt F. Cross
    institute: msu
  - name: James M. Hood
    institute: osu
  - name: Jonathan P. Benstead
    institute: bama
  - name: Alex D. Huryn
    institute: bama
  - name: Daniel Nelson
    institute: usu
  - name: Jon S. Olafsson
    institute: veidi
  - name: Gisli M. Gislason
    institute: reyk
institute:
  - msu: Department of Ecology, Montana State University, Bozeman, MT USA
  - glrc: Current `address:` Great Lakes Research Center, Michigan Technological University, Houghton, MI USA
  - osu: Department of Evolution, Ecology, and Organismal Biology, The Ohio State University, Translational Data Analytics Institute, The Aquatic Ecology Laboratory, Columbus, OH 43212, USA
  - bama: Department of Biological Sciences, University of Alabama, Tuscaloosa, AL  35487, USA
  - usu: National Aquatic Monitoring Center, Department of Watershed Sciences, Utah State University, Logan, UT 84322, USA
  - veidi: Institute of Marine and Freshwater Fisheries, Reykjavik, Iceland
  - reyk: Univeristy of Iceland, Institute of Life and Environmental Sciences, Reykjavik, Iceland
output:
   pdf_document:
     keep_tex: true
     pandoc_args:
       - '--lua-filter=scholarly-metadata.lua'
       - '--lua-filter=author-info-blocks.lua'
   word_document:
      reference_docx: working_docx_template.docx
      toc: no
      pandoc_args:
      - '--lua-filter=scholarly-metadata.lua'
      - '--lua-filter=author-info-blocks.lua'
   html_document: default
   pandoc_args:
      - '--lua-filter=scholarly-metadata.lua'
      - '--lua-filter=author-info-blocks.lua'
header-includes:
- \usepackage{lineno}
- \usepackage{amsmath}
- \usepackage{indentfirst}
- \linenumbers
indent: true
linestretch: 1
bibliography: refs.bib
link-citations: no
link-color: grey
csl: ecology.csl
---

```{r import general objects, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(knitr)

```
<!--- Title page details --->
<!-- \setlength\parindent{24pt}\setlength{\parskip}{0.0pt plus 1.0pt} -->

\newpage

<!--- this is a note in Rmarkdown --->

# Abstract

Warming temperatures are altering communities and trophic networks globally. While the influence of warming in food webs is often context-dependent, increasing temperatures are predicted to alter food webs and ecosystems in a number of general and fundamental ways, among them, 1) decreasing organism body size and 2) increasing metabolic rates. Both body size and metabolic rate are important drivers of many ecological patterns. Therefore, warming-induced changes have the potential to propagate through countless ecosystem processes thereby altering the distribution of food webs fluxes, food web stability, and potentially the importance of environmental and biological factors in community assembly. Here, we quantify the patterning and relative distribution of organic matter fluxes through stream food webs spanning a natural ~25$^\circ$C temperature gradient. We then related patterns in fluxes to species and community traits (body size, *M* and biomass turnover, *P:B*) within and across ecosystems. We predicted 1) fluxes would skew towards smaller *M* and higher *P:B* both across and within ecosystems and 2) fluxes would be more skewed at higher temperatures. Across the temperature gradient, communities in warmer streams were composed of smaller-bodied and higher-turnover populations on average. Additionally, material fluxes of warmer streams were increasingly skewed towards high-turnover populations *within* the community, showing higher temperatures restructured organic matter fluxes in both an absolute and relative sense. Lastly, in warmer ecosystems the relative distribution of organic matter fluxes appears to be increasingly 'non-random', evidence of potentially stronger selection for these traits with increasing temperature. The emerging picture is a warmer world that is both smaller and faster. Our study lends further support to this pattern and suggests that temperature will become an increasingly important environmental filter on warming communities in the future.

\newpage

# Introduction

<!--- warming and effects in food webs --->
<!--- Speeding up of food web: Species levels--->
Increasing global temperatures are altering the provisioning and maintenance of ecosystem services by modifying the network of interactions among species that underpin ecosystem functions [@brose2012; @woodward2010; @deruiter1995; @thompson2012]. Across global climate gradients, temperature mediates the dynamics and stability of food webs [@baiser2019] by altering the acquisition and allocation of resources among species [@zhang2017] and ultimately the magnitudes and relative distribution of biomass and fluxes among species and trophic levels [@may1972; @mccann1998; @barnes2018; @gibert2019a]. Temperature's effects permeate across levels of biological organization from its control on individual metabolic rates [@gillooly2001; @brown2004] and biological activity (e.g., attack rate, handling time, growth rates, etc.; @dell2014, as an environmental niche filter of community assembly and indirectly through the distribution of species traits, such as body size, within and across species [@bideault2019; @nelson2017].

<!--- Connect traits to the 'speed' of ecosystem energy fluxes--->
In fact, reduced organismal body size with warming is considered a 'universal' response to climate change [@atkinson1994; @gardner2011; @daufresne2009]. Body size reductions arise from multiple mechanisms acting at different levels of organization, such as the increased relative abundance of smaller species within warmer communities [@bergmann1848], or smaller individuals in warmer populations [@james1970], or through reduced body size of warmer individuals [@atkinson1994]. Temperature-size relationships (TSR) are likely to influence the distribution of body sizes both across and within ecosystems, such that warmer communities should contain smaller species and populations, on average, and smaller organisms should be more dominant within a community. These changes can have important implications for ecosystems pattern and processes because body size is a strong determinant of an organism's biology [@peters1983] influencing, life history patterns [@zeuss2017; @altermatt2010; @nelson2020b], and developmental [@angilletta2004] and metabolic rates [@brown2004; @gillooly2001].

<!--- Write the main goals of the paragraph--->
Organismal metabolic rate, in addition to being controlled by body size, is strongly influenced by temperature [@gillooly2001]. Therefore, temperature may alter metabolic rate indirectly through reductions in body size, as well as directly through its effects on subcellular kinetics [@bideault2019; @osmond2017]. The interactive effect of these processes has been shown to modulate ecosystem patterns through effects on population abundance [@bernhardt2018], consumer-resource interactions [@bideault2019], and food web structure [@gibert2019a]. Importantly, the kinetic effects of temperatures are tied to many biological processes [@dell2014], among them growth rate [@gillooly2001], developmental rate [@zuo2012; @nelson2020b], voltinism [@zeuss2017], and population turnover rate [@huryn2007; @brown2004]. As such, the emerging picture suggests a smaller, faster world in which warming "speeds up" ecosystem processes through the compounded effects of smaller body size and higher turnover rates.*possibly simplify the paragraph and combined with above*

Yet, considerable uncertainty remains in the predicted short- and long-term effects of climate warming, especially at higher levels of organization such as communities and food webs [@woodward2010; @walther2002]. For example, species interactions in food webs may modulate species' TSRs [@delong2014], leading to varied responses among species and trophic levels [@ohlberger2013]. Additionally, warming-induced body size reductions may act as a stabilizing process in some consumer-resource interactions through reduced consumer:resource biomass ratios [@osmond2017] and reductions in consumer growth rates relative to resource supply [@kozlowski2004; @delong2012a; @mccann2011; @greyson-gaito2022]. 
Therefore, food web processes may impart varying selective pressures on the distribution of body sizes and population turnover within communities. If strong, these pressures may leave distinct imprints on community structure and the distribution of energy fluxes within food webs with potential implications for the stability and functioning of ecosystems on a warming planet [@petchey1999; @fussmann2014].

Here, we measured the patterning and distribution of energy fluxes within invertebrate food webs across a natural stream temperature gradient (\~5--28$^\circ$C). Previous research in these streams has shown a strong positive effect of temperature on primary production both among streams [@demars2011; @padfield2017] and within streams seasonally
[@ogorman2012; @hood2018]. Consumers rely largely on autochthonous resources [@ogorman2012; @nelson2020] and therefore the dynamics of primary production have a strong control on consumer energy demand [@junker2020]. As such, we predicted annual energy fluxes of consumers to scale with among-stream patterns in resource availability and consumer energy demand and increase with temperature across streams. We hypothesized temperature to be a strong environmental filter of community assembly and the distribution of energy and organic matter fluxes, especially at the extremes. From this we made a number of predictions regarding the patterning of energy fluxes within and across communities of different temperature, with particular focus on two species traits: body size and population biomass turnover (production:biomass ratios, *P:B*). First, we predict warmer temperatures should favor smaller and faster turnover species leading to a decrease in body sizes and increase in *P:B* on average across communities. Second, within communities energy fluxes should be dominated by smaller, higher turnover species at warmer temperatures. Third, we hypothesized that the selective pressure from environmental temperature on body sizes and population turnover would be greatest at temperature extremes, therefore, the patterning of energy fluxes will be 'non-random' at coldest and warmest temperatures.   

# Methods

## Invertebrate sampling

We sampled macroinvertebrate communities approximately monthly from July 2011 to August 2012 in four streams and from October 2010 to October 2011 in two streams used in a previous
study (*n* = 6 streams). The two streams were part of an experiment beginning October 2011, therefore overlapping years were not used to exclude the impact of experimental
manipulation [@nelson2017; @nelson2017a]. Inter-annual comparisons of primary and secondary production in previous studies showed minimal differences among years in
unmanipulated streams, suggesting that combining data from different years would not significantly bias our results [@nelson2017; @hood2018]. We collected five Surber samples
(0.023 m^2^, 250 $\mu$m mesh) from randomly selected locations within each stream. Within the sampler, inorganic substrates were disturbed to \~10 cm depth and invertebrates and
organic matter were removed from stones with a brush. Samples were then preserved with 5% formaldehyde until laboratory analysis. In the laboratory, we split samples into coarse
(\>1 mm) and fine (\<1 mm but \>250 $\mu$m) fractions using nested sieves and then removed invertebrates from each fraction under a dissecting microscope (10--15 x magnification).
For particularly large samples, fine fractions were sub-sampled (1/2--1/16th) using a modified Folsom plankton splitter prior to removal of invertebrates. Subsamples were scaled to
the rest of the sample assuming similar abundance and body size distributions. Macroinvertebrates were identified to the lowest practical taxonomic level (usually genus) with
taxonomic keys [@peterson1977; @merritt2008; @andersen2013]. Taxon-specific abundance and biomass were scaled to a per meter basis by dividing by the Surber sampler area.

## Secondary Production

Daily secondary production of invertebrate taxa was calculated using the instantaneous growth rate method [IGR, @benke2017]. Growth rates were determined using taxon appropriate
approaches described in [@junker2020]. Briefly, growth rates of common taxa (e.g., Chironomidae spp., *Radix balthica*, etc.) were determined using *in situ* chambers [@huryn1986].
Multiple individuals (*n* = 5--15) within small size categories (\~1 mm length range) were photographed next to a field micrometer, placed into the stream within pre-conditioned
chambers for 7--15 days, after which they were again photographed. Individual lengths were measured from field pictures using image analysis software [@schindelin2012], and body
lengths were converted to mass (mg ash-free dry mass [AFDM]) using published length-mass regressions [@benke1999; @ogorman2012; @hannesdottir2013]. Growth rates (*g*, d^-1^) were
calculated by the changes in mean body size (*W*) over a given time interval (*t*) with the following equation:

$$g = log_e ( W_{t+\Delta t} / W_t) / \Delta t$$

Variability in growth rates was estimated by bootstrapping through repeated resampling of individual lengths with replacement (*n* = 1000). For taxa which exhibit synchronous growth
and development (e.g., Simuliidae spp., some Chironomidae spp., etc.), we examined temporal changes in length-frequency distributions and calculated growth rates and uncertainty
using a bootstrap technique similar to that described in Benke and Huryn [-@benke2017]. Individual Lengths were converted to mg AFDM using published length-mass regression cited
above and size-frequency histograms were visually inspected for directional changes in body size through time. For each date, size-frequency distributions were resampled with
replacement and growth rates estimated from equation 1. We prevented the calculation of negative growth rates by requiring $W_{t + \Delta t}$ \> $W_t$. To estimate
growth rates of taxa for which growth could not be estimated empirically, we developed stream-specific growth rate models by constructing multivariate linear regressions of
empirical growth data against body size and temperature within each stream. To estimate uncertainty in production of each taxon, we used a bootstrapping technique that resampled
measured growth rates, in addition to abundance and size distributions from individual samples. For each iteration, size-specific growth rates were multiplied by mean
interval biomass for each size class and the number of days between sample dates to estimate size class-specific production. For each interval, size classes were summed for each
taxon to calculate total population-level production. Intervals were summed to estimate annual secondary production.

## Diet analysis

Macroinvertebrate diets were quantified for dominant taxa in each stream. We focused on numerically abundant taxa and/or taxa with relatively
high annual production. A minimum of five individuals were selected from samples, and, when possible included individuals of different size classes to account for ontogenetic
shifts in diet. We included individuals from different seasons to capture concurrent ontogenetic and seasonal changes. For small-bodied taxa, we combined multiple individuals (*n*
= 3--5) to ensure samples contained enough material for quantification. We used methods outlined in Rosi-Marshall [-@rosi-marshall2016] to remove gut tracts and prepare gut contents for quantification. Briefly, we removed the foregut from each individual or collection of individuals and sonicated contents in water for 30 seconds. Gut content slurries were filtered
onto gridded nitrocellulose membrane filters (Metricel GN-6, 25 mm, 0.45 $\mu$m pore size; Gelman Sciences, Ann Arbor, MI, USA), dried at 60 $^\circ$C for 15 min, placed on a
microscope slide, cleared with Type B immersion oil, and covered with a cover slip. We took 5--10 random photographs under 200--400x magnification, depending on the density of
particles, using a digital camera mounted on a compound microscope. From these photographs we identified all particles within each field and measured the relative area of particles
using image analysis software [@schindelin2012]. We classified particles into six categories: diatoms, green and filamentous algae, cyanobacteria, amorphous detritus, vascular and non-vascular
plants (e.g., bryophytes), and animal material and then calculated the proportion of each food category in the gut by dividing their summed area by the total area of all particles. Gut
contents of many predators were empty or contained unidentifiable, macerated prey. For these taxa, we assumed 100% animal material.

To estimate variability in diet compositions and to impute missing values for non-dominant, yet present, taxa, we modeled the diet proportions within each stream using a
hierarchical multivariate model [@fordyce2011; @coblentz2017]. Here, the diet of a consumer population, *i*, in stream, *j*, is a multinomial vector,$\overrightarrow{y_{ij}}$, of
$$\overrightarrow{y_{ij}} \sim Multinomial(\overrightarrow{p_{ij}}, n_{ij})$$ $$\overrightarrow{p_i} \sim Dirichlet(\overrightarrow{q_i} \times  \alpha) $$ where, $\overrightarrow{p_i}$, is
a vector of consumer diet proportions, $\overrightarrow{q_i}$ is a vector of the population's diet proportions and $\alpha$ is a concentration parameter of the Dirichlet process.
We used uniform priors for $\overrightarrow{q_i}$ and $\alpha$, $$\overrightarrow{q_i} \sim Dirichlet(\overrightarrow{\textbf{1}})$$ $$\alpha \sim Uniform(0,\textit{c})$$ where,
$\overrightarrow{\textbf{1}}$ is a vector of ones the same length of basal resource types and $\textit{c}$ is the assumed concentration value. Models were fit in Stan with the 'brms' package in R [@burkner2017]. For non-dominant taxa, diet proportions were imputed
from the hierarchical model by resampling from posterior distributions. Importantly, this process allowed to maintain the hierarchical structure of the data when imputing missing values.

From modeled diet compositions, we estimated trophic redundancy within and across stream food webs by calculating proportional similarities (*PS*; @whittaker1952 among modeled diet estimates. Proportional similarities were calculated as:

$$ PS = 1 - 0.5 \sum_{j=1}^S|p_{x,i} - p_{y,i}|$$

where, *p~x,i~* is the proportion of food resource *i* in the diet of taxon *x*, *p~y,i~* is the proportion of food resource *i* in the diet of taxon *y*, and there are *S* food categories. Proportional similarity was calculated across all taxa within a stream based on modeled diet contributions from each taxon. To calculate *PS* among streams we sampled 1000 estimates of the mean stream-level diet proportions for each stream and calculated *PS* for each. 

## Organic Matter Consumption Estimates

Consumption fluxes (g m^-2^ t^-1^) were calculated using the trophic basis of production method [TBP, @benke1980]. Taxon-specific secondary production estimates were combined with
diet proportions, diet-specific assimilation efficiencies, *AE~i~*, and assumed net production efficiencies, *NPE*, to estimate consumption of organic matter. For each food
category, *i*, diet proportions were multiplied by the gross growth efficiency ($GGE_{i} = AE_{i} * NPE$) to calculate the relative production attributable to each food
category. The relative production from each food type was then multiplied by the interval-level production and finally divided by $GGE_{i}$ to estimate consumption of organic
matter from each food category by a consumer [@benke1980]. Consumption was calculated for each taxon across sampling intervals (typically \~1 month). Total interval consumption was
calculated by summing across all taxa, while annual consumption was calculated by summing across all taxa and intervals. Variability in consumption estimates was estimated through
a Monte Carlo approach, wherein bootstrapped vectors of secondary production for each taxon (see *Secondary production* methods above) were resampled and consumption estimated with
the TBP method using modeled diet proportions (see *Diet analysis* above), diet-specific assimilation efficiencies, and net production efficiency. Variability in *AE~i~* was
incorporated by resampling values from beta distributions fit to median and 2.5% and 97.5% percentiles for each diet item: diatoms = 0.30 (95% percentile interval (PI): 0.24-0.36),
filamentous and green algae = 0.30 (95% PI: 0.24-0.36), cyanobacteria = 0.10 (95% PI: 0.08-0.12), amorphous detritus = 0.10 (95% PI: 0.08-0.12), vascular and non-vascular plants
(bryophytes) = 0.1 (95% PI: 0.08-0.12), and animal material = 0.7 (95% PI: 0.56-0.84)[@welch1968; @cross2007; @cross2011; @benke1980; @benke1997]. Variability in *NPE* was
incorporated by resampling values from an assumed beta distribution with median *NPE* = 0.45 (95% PI = 0.4-0.5). Beta distributions were fit using the 'get.beta.par()' function
within the *rriskDistributions* package [@belgorodski2017].

## Quantifying the distribution of food web fluxes

### Evenness Among consumers

To visualize and quantify how evenly OM fluxes were distributed among consumers within a stream, we constructed Lorenz curves [@lorenz1905] on ordered relative consumption fluxes, such that in a community with $S$ species and the relative consumption of species *i*, $p_i$, is ordered $p_1 \leq p_2 \leq ... p_S$. The Lorenz curve plots how a value, in this case OM flux, accumulates with increasing cumulative proportion of species. In a community with perfectly equal distribution of OM consumption among species, the Lorenz curve is simply a straight diagonal line. Deviation from perfect equality was calculated as the Gini coefficient [@gini1921], normalized for differences in $S$ among streams, $G^*$ [@solomon1975; @chao2019]: 

$$ G^* = (2 \sum_{i = 1}^S ip_i -2)/(S-1)$$ 

where $G^*$ represents an index of relative evenness of OM fluxes bounded between zero and one--one representing a community with exactly equal proportion of total community OM flux for all species ($1/S$), and a value of zero where total community flux is attributed to a single species. 

### Distribution of OM fluxes in relation to species' traits

We predicted that warming would favor species with smaller body size and higher population turnover and therefore OM fluxes would be skewed towards small body size (*M*) and higher *P:B* across and within communities. Across communities, we assessed the relationships between mean annual temperature ($^\circ$C) and mean population *M* and *P:B* of each community with bootstrapped linear regressions. Here, values of population *M* or *P:B* were resampled with replacement for each species within each stream. The mean of all populations within a stream was calculated and a linear model was fit between *log~e~*-transformed *M* or *P:B* and mean annual temperature. Response variables *M* and *P:B* were transformed to meet the assumption of normally distributed residual variation.

To quantify the distribution of energy fluxes _**within**_ a community, we assessed if relative OM flux was skewed towards populations with lower or higher relative *M* or  *P:B*. To do this, we ordered species based on within-stream ranking of annual population traits (i.e, $M$, $P:B$) and then calculated a measure of skewness, $Sk_{flux}$, based on quartiles of the distribution of OM fluxes in relation to species traits as:

$$Sk_{flux} = f_{Q0.75} - 2f_{Q0.5} + f_{Q0.25}/ f_{Q0.75}-f_{Q0.25}$$

where, $f_{Qx}$, is the cumulative flux at some quantile, $Qx$, of the community trait distribution. We repeated this analysis for all bootstrapped estimates of OM flux in all communities. Skewness coefficients exist in the range [-1, 1], where -1 indicates OM fluxes are skewed perfectly away from a trait and 1 indicates higher relative flux is perfectly associated with higher trait values. To determine if $Sk_{flux}$ with population *M* and *P:B* was related to mean annual stream temperature, we use bootstrapped beta regression with a simple transformation to meet the assumptions of the model, $(Sk_{flux} + 1)/2$, thereby standardizing values between 0 and 1. Model coefficients were back-transformed to estimate effect sizes.

To assess the strength of environmental filtering of species' traits within a community, we quantified how likely it was to observe such a skewed distribution in OM fluxes by random chance. Here, we predicted that communities with strong filtering for traits would exhibit highly skewed OM distributions that would be unlikely due to chance (i.e., 'non-random ordering'). In contrast, weak environmental filtering would produce OM fluxes with skew values that are likely due to random chance ('random ordering'). To accomplish this, we first had to account for statistical constraints that restrict the range of possible outcomes [\ i.e., feasible set, @haegeman2008; @diaz2021a], given the number of species and the relative distribution of OM fluxes within a community. The number of unique orderings of species increases to computationally intractable numbers very quickly (e.g., $S!$, 10 species ~3.6e^6^ unique orderings). Therefore, we chose to permute a random subset of each stream community's feasible set by randomly ordering species and calculating the skewness in the cumulative distribution of annual OM fluxes 100,000 times in each stream. The number of random orderings was chosen as a balance between characterizing the distribution of skewness values within each feasible set and computational and time constrains. This permuted set allowed us to calculate the probability of observing the empirical skewness, $Sk_{flux}$, in each stream compared to a random ordering given the distribution of relative OM flux. To assess the relationship between the probability of 'non-random ordering' and temperature, we again used beta regression on estimates of the probability of seeing the empirical $Sk_{flux}$ value or one more extreme based on random ordering of species in the permuted feasible set. Here, values can take the range between 0 and 1 so no transformation was necessary. As necessary, when we observed many values near 0 and 1, we implemented a zero-one inflated beta regressions in brms [@burkner2017] to test if the probability of observing the empirical $Sk_{flux}$ was associated with mean annual temperature across streams. We predicted increasingly 'non-random' distributions in OM fluxes with increasing temperature.

# Results

## Community OM fluxes

## Evenness of OM fluxes within streams 

## OM fluxes along species trait distributions among sites and taxa

# Discussion

# Acknowledgements

We are grateful to..

# References

<div id="refs"></div>

# Appendix

Spare(d) words
